### ISSUE TITLE
about the map of the detector

### ISSUE THREAD

**Issue by ZHUXUHAN** [DirtyHarryLYL/HOI-Learning-List#1]
how do you konw the map of the detector in different papers.

**Comment by DirtyHarryLYL** [comment]
Most papers did not report the performance of the object detector. Considering most works adopted the coco pre-trained faster rcnn, the performance gap may be minor. But if fine-tuning the detector on hoi train set with GT pair boxes, the detector would be totally different. 
Thus in the list, I divide them into two groups, one uses the off-the-shell detector, another one uses a unified detector&classifier or fine-tune the detector.

**Comment by ZHUXUHAN** [comment]
> Most papers did not report the performance of the object detector. Considering most works adopted the coco pre-trained faster rcnn, the performance gap may be minor. But if fine-tuning the detector on hoi train set with GT pair boxes, the detector would be totally different.
> Thus in the list, I divide them into two groups, one uses the off-the-shell detector, another one uses a unified detector&classifier or fine-tune the detector.

thanks a lot, I get it.

**Comment by DirtyHarryLYL** [comment]
In fact, it is really good to report the mAP of the detector, or we can use GT box to test the classification only to disentangle the detection and classification. Thus we can know which part of the hoi detection is improved exactly.
