### ISSUE TITLE
cad120 dataset

### ISSUE THREAD

**Issue by xunguo18** [DirtyHarryLYL/HOI-Learning-List#10]
hello, can you share a link for cad120 dataset ? The official website is closed now. Thanks a lot.

**Comment by DirtyHarryLYL** [comment]
Hi, we do not have data backup too. Perhaps you could try to email the authors for help?

**Comment by DirtyHarryLYL** [comment]
Or some other works on this benchmark may also have data backup?

**Comment by ddwhzh** [comment]
https://web.archive.org/web/20200916193814/http://pr.cs.cornell.edu/humanactivities/data.php

**Comment by ddwhzh** [comment]
> https://web.archive.org/web/20200916193814/http://pr.cs.cornell.edu/humanactivities/data.php

Get the download link through the web snapshot, and then download it through Thunder Cloud Drive.

**Comment by DirtyHarryLYL** [comment]
Resolved.
