### ISSUE TITLE
Serious issue on Zero-Shot HOI Detection.

### ISSUE THREAD

**Issue by zhihou7** [DirtyHarryLYL/HOI-Learning-List#11]
Thanks for your repository on HOI Learning. 

I find there is a serious issue in the current zero-shot HOI comparison. It is unfair to compare VCL with [Functional](https://arxiv.org/pdf/1904.03181.pdf). VCL has introduced a more robust compositional zero-shot setting, that is rare-first selection and non-rare first selection, in which the selection is fixed in the two settings from the tail and head classes. However, [Functional](https://arxiv.org/pdf/1904.03181.pdf) randomly select the unseen categories 5 times. Though they randomly select the unseen categories, the selected unseen categories are actually similar and thus ignore the extreme cases due to the long-tailed distribution in HICO-DET. **I have found this issue has misled massive following papers.** Hope you can correct that as soon as possible. I have not focused on HOI detection for a long time and did not catch this issue in time. Sorry for that.

Thanks for your time,

Best wishes,
Zhi Hou

**Comment by zhihou7** [comment]
Btw, [ATL(w/ affordance)](https://github.com/zhihou7/HOI-CL) use object datasets rather than affordance. ATL (w/ coco) is more suitable.

**Comment by DirtyHarryLYL** [comment]
Hi Zhi, thanks! Nice to meet you, very happy to see the suggestion.
Please feel free to propose an update to the table and ATL according to your kind advice.

**Comment by zhihou7** [comment]
Hi @DirtyHarryLYL, Thanks for your reply. I will try to require a pull request as soon as possible.

Regards,

**Comment by DirtyHarryLYL** [comment]
Hi Zhi, your request has been merged. Thanks for the contribution!
