### ISSUE TITLE
The issue about Object Detector

### ISSUE THREAD

**Issue by zhihou7** [DirtyHarryLYL/HOI-Learning-List#12]
Sincerely thanks for your contribution. 

Actually, I want to post a question: is there anyone who reimplement the object detector of [DRG](http://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123570681.pdf)? Actually, the repository has closed the issue. Therefore, I think it is unsuitable to include the results that use the DRG boxes on HOI detection. That might mislead the following works.

Regards,

**Comment by DirtyHarryLYL** [comment]
Thanks! I have updated some scores, please remind me or directly update the table if some scores are missed.

**Comment by zhihou7** [comment]
Thanks for your reply.
