### ISSUE TITLE
Share some Repositories found on github

### ISSUE THREAD

**Issue by ddwhzh** [DirtyHarryLYL/HOI-Learning-List#18]
Thank you very much for the summary.
Recently, I found some Repositories under the Human-object-interaction entry of github, mostly datasets, which I feel can enrich this list.
[CHORE](https://github.com/xiexh20/CHORE)
[behave-dataset](https://github.com/xiexh20/behave-dataset)
[2G-GCN](https://github.com/tanqiu98/2G-GCN)
[VidHOI](https://github.com/coldmanck/VidHOI)
It would be an honor to help you! Thank you。

**Comment by DirtyHarryLYL** [comment]
Thank you very much！VidHOI has been contained before but without the project link. I have added these useful works to the list.
