### ISSUE TITLE
Some works on HOI recognition and anticipation

### ISSUE THREAD

**Issue by Evm7** [DirtyHarryLYL/HOI-Learning-List#25]
Hi! Thanks a lot for maintaining this list. Your work is very helpful.

I would like to introduce you to two works on HOI detection and anticipation from video data: 

- [Human–object interaction prediction in videos through gaze following](https://evm7.github.io/HOIGaze-page/). Accepted in Journal of CVIU, 2023
- [HOI4ABOT: Human-Object Interaction Anticipation for Assistive roBOTs](https://evm7.github.io/HOI4ABOT_page/). Accepted in CORL, 2023

These works are rooted in their applications in robotics, where anticipating HOIs is really helpful for the robot decision-making process!

**Comment by DirtyHarryLYL** [comment]
Hi, thx for the suggestion. They are on the list now!
