### ISSUE TITLE
question regarding annotation of hico_det

### ISSUE THREAD

**Issue by monacv** [DirtyHarryLYL/HOI-Learning-List#4]
hello, thanks a lot for curating this dataset for HOI researchers.

I wonder why in this image, I see 4 occurrences of "pull kite" while I only see one?

out data/hico_20160224_det/sample_train_images/HICO_train2015_00037548.jpg and [371, 372, 374, 375, 375, 375, 375]
369  kite            assemble      
370  kite            carry         
371  kite            fly           
372  kite            hold          
373  kite            inspect       
374  kite            launch        
375  kite            pull          
376  kite            no_interaction

![Screenshot from 2021-04-09 01-07-40](https://user-images.githubusercontent.com/76495162/114131334-75171a80-98d0-11eb-9346-fba7eecc06e7.png)

**Comment by DirtyHarryLYL** [comment]
Looks like four 375 HOIs for four different human **boxes**.
You could visualize the annotations and the corresponding boxes to figure it out.
