### ISSUE TITLE
wrong images for repair bike?

### ISSUE THREAD

**Issue by monacv** [DirtyHarryLYL/HOI-Learning-List#5]
Hi do you know why we have wrong images for repair bike?
data/hico_20160224_det/images/train2015/HICO_train2015_00030009.jpg
![Screenshot from 2021-04-23 17-06-26](https://user-images.githubusercontent.com/76495162/115929736-482d4080-a456-11eb-98d7-f562136ac0ca.png)
this is not repair but has repair bike and carry bike labels

this image clearly is not repairing or carrying a bike

I check quite a couple and all seems to be consistently wrong for repair bike.

Other wrong examples
data/hico_20160224_det/images/train2015/HICO_train2015_00001762.jpg
![Screenshot from 2021-04-23 17-11-18](https://user-images.githubusercontent.com/76495162/115930182-04870680-a457-11eb-9e8c-5fb87ff37083.png)

data/hico_20160224_det/images/train2015/HICO_train2015_00033539.jpg
![Screenshot from 2021-04-23 17-12-25](https://user-images.githubusercontent.com/76495162/115930231-19fc3080-a457-11eb-968f-70cdf09626d4.png)

HICO_train2015_00012629.jpg
![Screenshot from 2021-04-23 17-13-04](https://user-images.githubusercontent.com/76495162/115930285-2ed8c400-a457-11eb-84aa-3965563f57d0.png)

**Comment by monacv** [comment]
also noticed that this image is labeled as wash bicycle

data/hico_20160224_det/images/train2015/HICO_train2015_00003345.jpg

![Screenshot from 2021-04-23 19-11-16](https://user-images.githubusercontent.com/76495162/115938167-baf2e780-a467-11eb-89b9-6da556dae0ac.png)

I think there are two problems with this image:
1. there is no washing action
2. the human is so far away from the bike that basically there is no human-object interaction

**Comment by DirtyHarryLYL** [comment]
Hi, this may be wrong annotations from hico-det, if the label file is the one **corresponding to this image**. 
You could fix the labels in this situation. As the large-scale annotations, sometimes the annotators may give wrong answers.

**Comment by ASMIftekhar** [comment]
@monacv hello, do you have any statistics about how many of them are actually wrong?
