### ISSUE TITLE
How to implement "Learning Models for Actions and Person-Object Interactions with Transfer to Question Answering"

### ISSUE THREAD

**Issue by ifmaq1** [DirtyHarryLYL/HOI-Learning-List#8]
Hi, this repository stated the paper named

"Learning Models for Actions and Person-Object Interactions with Transfer to Question Answering"

it also has its pretrained model and data given. How do we use the given  pretrained model and data associated with it to extract the action detection on our **customized dataset**

Any repository that you can suggest?

**Comment by DirtyHarryLYL** [comment]
In [HAKE](https://github.com/DirtyHarryLYL/HAKE-Action/tree/Image-level-HAKE-Action), a Caffe model with docker is provided. It is based on the code of this ECCV'16 work. You may cook your own project with these tools.

**Comment by ifmaq1** [comment]
Thanks.
